min_group_size: 30
significance_threshold: 1.96
alpha_level: 0.05

protected_attributes:
  - country
  - age
  - religion
  - gender

intersections:
  - gender_x_religion
  - gender_x_country
  - religion_x_country
  - age_x_gender

reference_groups:
  country: Pakistan
  age: 40
  religion: Muslim
  gender: Male

data_paths:
  post_brexit: "/data/shil6369/gov_scraper/inference/results/processed/full_inference_llama3_8b_post_brexit_2019_2025_instruct_20250629_135630_20250630_124832/successful_extractions.json"
  pre_brexit: "/data/shil6369/gov_scraper/inference/results/processed/full_inference_llama3_8b_pre_brexit_2013_2016_instruct_20250629_190319_20250630_112248/successful_extractions.json"

metrics:
  representation:
    - statistical_parity
    - counterfactual_flip_rate
  error_based:
    - equal_opportunity
    - false_positive_rate
    - equalized_odds_l2
    - agreement_rate

analyze_by_topic: true
analyze_by_meta_topic: false

output_formats:
  - json
  - csv
  - html

visualization:
  figure_size: [12, 8]
  dpi: 300
  color_palette: viridis
  save_formats:
    - png
    - pdf 